### ISSUE TITLE
Get actual breakpoints from defined BS4 css custom properties.

### ISSUE THREAD

**Issue by mattez** [Johann-S/bs-breakpoints#1]
Is code getting actual breakpoints also from defined BS4 CSS custom properties? It seems they are only hardcoded inside script? Or I'm wrong?
Of course, values of breakpoints may vary from project to project. So the definition in the script would then have to be changed.
As you know, there are available CSS custom properties from which the current breakpoints values can be read:
```
:root {
...
    --breakpoint-xs: 0;
    --breakpoint-sm: 576px;
    --breakpoint-md: 768px;
    --breakpoint-lg: 992px;
    --breakpoint-xl: 1200px;
...
}
```

What do you think?

Discussion o about this https://github.com/twbs/bootstrap/issues/25124#issuecomment-354547658

**Comment by Johann-S** [comment]
You're right currently it's hardcoded, and that's an awesome idea, I'll add that 👍

**Comment by Johann-S** [comment]
Done here: https://github.com/Johann-S/bs-breakpoints/commit/69c4730c9ca8d7266267e6abdc4348f15f52d16d and https://github.com/Johann-S/bs-breakpoints/commit/818394b03cbad62d11b63fb990b4847005904171

**Comment by Johann-S** [comment]
@mattez I'll make a release soon 😉

**Comment by mattez** [comment]
I recommend promoting this new feature somehow in the README. You will differ from your competitors :)

**Comment by Johann-S** [comment]
done 😉 thanks 👍
