### ISSUE TITLE
init.bs.breakpoint not working under iOS 7.1.2

### ISSUE THREAD

**Issue by dougloj** [Johann-S/bs-breakpoints#13]
Hi I ran the following jQuery code under Safari on an iPhone 4 with iOS 7.1.2:

$(window).on('init.bs.breakpoint', function (e) {
    alert('init ' + e.breakpoint);
 })

e.breakpoint ended up being null.

Do you know is bs-breakpoints works under iOS 7 or do you know what the issue may be?

**Comment by Johann-S** [comment]
Hi @dougloj,

It should totally work, can you check that example: https://cdpn.io/Johann-S/debug/zYYKxKW ?

Does it works on iOS 7 ?

**Comment by dougloj** [comment]
Sorry for the delay in replying. When I go to  https://cdpn.io/Johann-S/debug/zYYKxKW on my iPhone 4 running iOS 7.1.2, I get an "Unsupported Browser" message.

**Comment by Johann-S** [comment]
since v2 is out, I'm closing this issue
