### ISSUE TITLE
bsBreakpoint is not defined

### ISSUE THREAD

**Issue by Sogl** [Johann-S/bs-breakpoints#3]
Hello @Johann-S !

I tried to install your library to my BS4 project without success. I use `laravel mix` (webpack based) compilation. 

All my js files:
![image](https://user-images.githubusercontent.com/7556290/55690058-15aa6b00-5995-11e9-9973-69289801599d.png)
becomes one another big `app-landing.js` file
![image](https://user-images.githubusercontent.com/7556290/55690212-fad8f600-5996-11e9-9f0d-5b7d335b19b2.png)
that I include before `</body>`:
```blade
...
        </main>

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <script src="{{ mix('landing/js/app-landing.js') }}"></script>
    </body>
</html>
```

`app-landing.js` (1st image) content:
```js
require('./bootstrap');
require('./custom');
```

In `bootstrap.js` file I put your library line. Full file content:
```js
try {
    window.$ = window.jQuery = require('jquery');
    require('bootstrap');
    //!!!here
    require('bs-breakpoints');
    require('jquery.easing');

    //lg
    require('lightgallery');
    require('lg-zoom');

    //fontawesome
    require('./fontawesome');
} catch (e) {}
```

And in `custom.js` I put two lines:
```js
...
//all loaded
$(document).ready(function() {
    console.log('loaded');
    bsBreakpoints.init();
    console.log(bsBreakpoints);
...
```

Finally in console:
![image](https://user-images.githubusercontent.com/7556290/55690188-c36a4980-5996-11e9-92bf-5834931d650a.png)

What I'm doing wrong?

p.s. https://github.com/sachinchoolur/lightGallery library works fine in same situation.

**Comment by Johann-S** [comment]
Hi @Sogl,

First of all thanks for using (or trying to use) my libs 👍 😄 

Here you have to do the same you did for jQuery, something like:

```js
 window.bsBreakpoints = require('bs-breakpoints');
```

**Comment by Sogl** [comment]
Works like a charm. Thanks!

Now I have one another question. 
Part of my code in `custom.js` with workaround and without your library:
```js
$('nav').on('show.bs.collapse', function () {
    if (($(window).width() <= 991) && ($(window).scrollTop() <= 20)) {
        $("nav").addClass("bg-dark");
    }
});
```

How to clearly say in code that I want sizes "middle or smaller than middle"?
Like in sass `@include media-breakpoint-down(md) {` notation.

Do I need an object `if ((bsBreakpoints.getCurrentBreakpoint() in ScreensObj)) { ... }` or something to archieve that?

**Comment by Johann-S** [comment]
You can achieve that, like that:

```js
var currentBreakPoint = breakPoints.detectBreakpoint()
if (currentBreakPoint === 'middle' || (currentBreakPoint === 'small' || currentBreakPoint === 'xSmall')) {
```

I hope it'll help you 👍

**Comment by Johann-S** [comment]
@Sogl if you have any other questions do not hesitate 👍
