### ISSUE TITLE
Doesn't work with Bootstrap 5

### ISSUE THREAD

**Issue by UPLYNXED** [Johann-S/bs-breakpoints#37]
Bootstrap 5 adds the `bs-` prefix by default, turning properties like `--breakpoint-sm` into `--bs-breakpoint-sm`.
To not lose BS4 support I recommend checking if the `--breakpoint-sm` formatted property names return NaN, and then attempting to get the prefixed ones.

See my PR #36

**Comment by UPLYNXED** [comment]
If you'd like to implement fuller BS5 compatibility, you could consider adding an optional config file of some kind to allow users to set a custom prefix if they've changed it in the BS5 Sass build.

**Comment by lanesCSO** [comment]
has there been any update on BS5 support?

**Comment by UPLYNXED** [comment]
> has there been any update on BS5 support?

@lanesCSO
I know I replied to you on the PR comment already too but I'll just repeat it here for others who may only read this issue:

I submitted a pull request ( #36 ) that adds Bootstrap 5 support.
I have a release on my fork of the repo that you can use in the meantime.
https://github.com/UPLYNXED/bs-breakpoints/releases/tag/v1.1.1-bs5

**Comment by Johann-S** [comment]
fixed in v2: https://github.com/Johann-S/bs-breakpoints/releases/tag/v2.0.0
